### ISSUE TITLE
The Shadow Scope header different in different pages

### ISSUE THREAD

**Issue by timstasevich** [dpbam/shadow-scope#24]
I noticed 'The Shadow Scope' appears on main index.html, but in other places (e.g. learn.html), it is 'the Shadow Scope.' Nice to make it all consistent.

**Comment by timstasevich** [comment]
Notice 'The Shadow Scope' header it is a link (that responds to mouse over) on index.html, but not on other pages. Would be nice if you can link back to home from other pages by clicking on 'The Shadow Scope' from all other pages.

**Comment by dpbam** [comment]
This has since been fixed. Noticed that too. Good eye.
