### ISSUE TITLE
Slide show pictures different sizes

### ISSUE THREAD

**Issue by timstasevich** [dpbam/shadow-scope#25]
Any way to somehow enforce the height of the slide show pictures to be a fraction of the outer container? That way all will have the same height, but widths will change. This will prevent the resizing of the webpage that currently occurs as the slide show moves through the different sized images. One potential issue is that some images might now become too wide (but this shouldn't be a problem unless the inputted image is really wide compared to tall).

**Comment by timstasevich** [comment]
Also, I notice that the slide show automatically moves, which is fine, but now the arrows don't seem to work, so once cannot easily choose or explore the images by clicking on the '<' and '>' arrows that appear when your mouse hovers over the slide show image.

**Comment by dpbam** [comment]
I got rid of the arrows and resized all the images (now in a folder within that users images folder called "cropped-for-slideshow". Also, I slowed the slideshow. Let me know what you think.

**Comment by timstasevich** [comment]
Should I be pulling from main? It's not appearing. It did earlier, actually, but now it seems back to how it was?

**Comment by dpbam** [comment]
Hmmm. Yeah, it's in the develop branch. Can you pull the develop branch down?

**Comment by timstasevich** [comment]
Yeah, I figured out how to pull from a different branch on VS Code: Pull,Push > Pull from > origin (then all branches from origin will appear, such as origin/develop. We'll have to teach that to the others. 

Anyways, looks good! I like the slower slide show.

**Comment by timstasevich** [comment]
Only thing I notice is on a really wide screen, the picture seems pretty small. Seems like it could get a bit bigger when the screen gets bigger (like my wide screen).

**Comment by timstasevich** [comment]
I take that back....it does scale. Just when I switch immediately to full screen it keeps it small, but then when I zoom in, it becomes nice and big.... Anyways, seems fine the way it is!

**Comment by dpbam** [comment]
That's weird. I'll see if I can figure out why that is.

**Comment by timstasevich** [comment]
Not a big deal... I don't think there's a need to fix.

**Comment by dpbam** [comment]
Ok cool. I'll close this issue, then. Also, check out the preview cards images in phone size. Let me know if that works for you.
